services:
  nginx:
    container_name: mtestx1
    image: php-nginx-alpine
    volumes: 
      - ./src/index.php:/var/www/html/index.php
      - ./nginx-secure.conf:/etc/nginx/http.d/default.conf
    ports:
      - 8958:80
    
  postgres:
    container_name: postgresql
    image: postgres:16
    ports:
      - 5554:5432
    command:  postgres -c max_connections=300
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
